/**
 * Catalyst Repository — State management for Catalyst Intelligence.
 *
 * Thin wrapper over the shared analysis repository.
 * Repository key convention: "catalyst-intelligence:<TICKER>"
 *
 * IMPORTANT:
 *   - TICKER here is the display symbol (e.g. "NOVO B", "MSFT", "MAERSK B").
 *   - Keys are stored lowercase-normalized to avoid case mismatches.
 *   - Driver profiles use a separate key: "company-driver-profile:<TICKER>"
 */

import { analysisRepository } from "./analysis-repository.js";
import type { CatalystState, CompanyDriverProfile } from "./catalyst-types.js";

// ── Key helpers ────────────────────────────────────────────────────────────────

export function catalystStateKey(ticker: string): string {
  return `catalyst-intelligence:${ticker.trim().toUpperCase()}`;
}

export function driverProfileKey(ticker: string): string {
  return `company-driver-profile:${ticker.trim().toUpperCase()}`;
}

// ── Catalyst state ─────────────────────────────────────────────────────────────

/**
 * Read catalyst state for a ticker. Returns undefined if not yet screened.
 */
export function getCatalystState(ticker: string): CatalystState | undefined {
  const key = catalystStateKey(ticker);
  const entry = analysisRepository.get<CatalystState>(key);
  return entry?.result;
}

/**
 * Save catalyst state for a ticker. Creates a new repository entry if
 * none exists; updates materialVersion only when opportunityState changes.
 */
export function saveCatalystState(ticker: string, state: CatalystState): void {
  const key = catalystStateKey(ticker);
  const existing = analysisRepository.get<CatalystState>(key);
  const prevState = existing?.result?.screening?.preliminaryState;
  const newState  = state.screening?.preliminaryState;

  // Treat a meaningful state change as material (triggers downstream cascades)
  const isMaterial = prevState !== newState;

  if (isMaterial) {
    analysisRepository.save(key, state);
  } else {
    // Same opportunity state — bump updatedAt without changing materialVersion
    analysisRepository.saveSkipped(key);
    // Update the result in-place so reads get the latest facts/screening
    analysisRepository.save(key, state);
  }
}

/**
 * Get catalyst states for all tracked tickers.
 * Returns only entries that have been screened at least once.
 */
export function getAllCatalystStates(): CatalystState[] {
  return analysisRepository
    .getAll()
    .filter(e => e.moduleName.startsWith("catalyst-intelligence:"))
    .map(e => e.result as CatalystState)
    .filter(Boolean);
}

/**
 * Mark that a catalyst AI analysis was performed (advances lastAIAnalysisAt).
 * Called by the orchestrator after a successful deep analysis.
 */
export function markCatalystAIAnalysis(ticker: string, timestamp: string): void {
  analysisRepository.markAIAnalysis(catalystStateKey(ticker), timestamp);
}

// ── Company Driver Profile ─────────────────────────────────────────────────────

/**
 * Read the Company Driver Profile for a ticker.
 * Returns undefined if no profile has been generated yet.
 *
 * ARCHITECTURE NOTE:
 *   Driver profiles are generated by Company Monitor (full analysis path)
 *   or by a dedicated driver-profile enrichment step. They are NOT generated
 *   on every Company Monitor run — only when the profile is absent or stale.
 *   This is Part 2 functionality. Part 1 defines the interface and storage only.
 */
export function getDriverProfile(ticker: string): CompanyDriverProfile | undefined {
  const key = driverProfileKey(ticker);
  const entry = analysisRepository.get<CompanyDriverProfile>(key);
  return entry?.result;
}

/**
 * Save a Company Driver Profile for a ticker.
 */
export function saveDriverProfile(ticker: string, profile: CompanyDriverProfile): void {
  const key = driverProfileKey(ticker);
  analysisRepository.save(key, profile);
}

/**
 * Check whether a driver profile exists and is reasonably fresh.
 * @param maxAgeHours  Maximum age in hours before a profile is considered stale.
 */
export function isDriverProfileFresh(ticker: string, maxAgeHours = 168): boolean {
  const key = driverProfileKey(ticker);
  const entry = analysisRepository.get<CompanyDriverProfile>(key);
  if (!entry) return false;
  const ageMs = Date.now() - new Date(entry.updatedAt).getTime();
  return ageMs < maxAgeHours * 3_600_000;
}
