import { Router, type IRouter } from "express";
import healthRouter from "./health";
import marketMonitorRouter from "./market-monitor";
import eventMonitorRouter from "./event-monitor";
import newsMonitorRouter from "./news-monitor";
import sectorMonitorRouter from "./sector-monitor";
import companyMonitorRouter from "./company-monitor";
import portfolioManagerRouter from "./portfolio-manager";
import portfolioAnalyzerRouter from "./portfolio-analyzer";
import opportunityFinderRouter from "./opportunity-finder";
import riskAnalyzerRouter from "./risk-analyzer";
import marketAlertsRouter from "./market-alerts";
import tradeDecisionEngineRouter from "./trade-decision-engine";
import tradeReviewRouter from "./trade-review";
import investorWatchRouter from "./investor-watch";
import commandBriefRouter from "./command-brief";
import marketIndicesRouter from "./market-indices";
import layoutsRouter from "./layouts";
import repositoryRouter from "./repository";
import settingsRouter from "./settings";
import systemLogRouter from "./system-log";
import automationRouter from "./automation";
import priceHistoryRouter from "./price-history";
import openaiUsageRouter from "./openai-usage";
import portfolioIntelligenceRouter from "./portfolio-intelligence";
import catalystIntelligenceRouter from "./catalyst-intelligence";
import companyEventsRouter from "./company-events";
import dataCoverageRouter from "./data-coverage";
import aiChatRouter from "./ai-chat";

const router: IRouter = Router();

router.use(healthRouter);
router.use(marketMonitorRouter);
router.use(eventMonitorRouter);
router.use(newsMonitorRouter);
router.use(sectorMonitorRouter);
router.use(companyMonitorRouter);
router.use(portfolioManagerRouter);
router.use(portfolioAnalyzerRouter);
router.use(opportunityFinderRouter);
router.use(riskAnalyzerRouter);
router.use(marketAlertsRouter);
router.use(tradeDecisionEngineRouter);
router.use(tradeReviewRouter);
router.use(investorWatchRouter);
router.use(commandBriefRouter);
router.use(marketIndicesRouter);
router.use(layoutsRouter);
router.use(repositoryRouter);
router.use(settingsRouter);
router.use(systemLogRouter);
router.use(automationRouter);
router.use(priceHistoryRouter);
router.use(openaiUsageRouter);
router.use(portfolioIntelligenceRouter);
router.use(catalystIntelligenceRouter);
router.use(companyEventsRouter);
router.use(dataCoverageRouter);
router.use(aiChatRouter);

export default router;
